language: python
dist: xenial  # required for Python >= 3.7
python:
- "3.0"
- "3.3"
- '3.5'
- '3.6'
- '3.7'
install:
- python setup.py install
- pip install coveralls
script:
- coverage run --source=animelyrics setup.py test
- coveralls